baseURL = "https://Lopez-504.github.io/jorgelopezblog/"
languageCode = "en-us"
title = "Jorge's Blog"
theme = "terminal"

#paginate = 5			# deprecated
[pagination]
  pagerSize = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  customCSS = ["css/custom.css"]

[languages]
  [languages.en]
    title = "Jorge's Blog"
    subtitle = "Physics, code, weather, and nocturnal thoughts"
    keywords = ""
    copyright = ""

    [languages.en.params.logo]
      logoText = "Jorge's Blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false      

# There's a problem here: when I set noClasses = true, the
# style = ashen works, but when noClasses = false, the 
# I get the default style but also the title and copy btn
# for the code block
  
  [markup.highlight]
    noClasses = false		#allows title and copy btn
    codeFences = true
    guessSyntax = true
    lineNos = true        
    style = "ashen"		#not responding	
    anchorLineNos = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNumbersInTable = true
    tabWidth = 4
    wrapperClass = 'highlight'
    
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
    
  [markup.asciidocExt]
    [markup.asciidocExt.attributes]
      source-highlighter = 'ashen'  